Name = input("Enter your name = ")
Age = input("Enter your age = ")
Age = int(Age)
Gender = input("Please input your gender = ")
Company = input("Write your company's name = ")
Salary = input("Write your in-hand without deductions = ")
List = (f"Your name is{Name} ,Your age is{Age},Your gender is{Gender},Your company name is{Company},Your salary is{Salary}")
print(List)
